language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer install
  - cd ./tests
  - mysql -e 'create database IF NOT EXISTS test;'
    
script: phpunit --configuration phpunit.travis.xml

branches:
  only:
    - develop
    - master
