language: php

env:
  - TRAVIS=true

php:
  - 7.1
  - 7.4

before_script:
  - composer install
  - cd ./tests
  - mysql -e 'create database IF NOT EXISTS test;'

script: phpunit --configuration phpunit.travis.xml

branches:
  only:
    - develop
    - master
