language: php

env:
  - TRAVIS=true

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer install
  - cd ./tests
  - mysql -e 'create database IF NOT EXISTS test;'

script: phpunit --configuration phpunit.travis.xml

branches:
  only:
    - develop
    - master
