name: PHPUnit Tests

on: [push]


permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.1',7.4']
    name: PHP ${{ matrix.php-versions }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - uses: php-actions/composer@v6

    - name: Tests
      uses: php-actions/phpunit@v3
      with:
        bootstrap: vendor/autoload.php
        configuration: test/phpunit.xml
        args: --coverage-text
        php_version: "7.1"
